# Generated by Django 5.1.2 on 2024-11-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsite', '0005_alter_enrollment_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='Subject',
        ),
    ]
