# Generated by Django 5.1.2 on 2024-11-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsite', '0006_remove_quota_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='Subject',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='quota',
            name='Status',
            field=models.CharField(max_length=100),
        ),
    ]
