# Generated by Django 5.1.2 on 2024-11-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mywebsite', '0007_quota_subject_alter_quota_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='Slot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quota',
            name='Status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='quota',
            name='Subject',
            field=models.CharField(max_length=100),
        ),
    ]
